### ISSUE TITLE
_start never called

### ISSUE THREAD

**Issue by drozzy** [exponentially/extreme_system#10]
It's weird, but it seems my app's start is never called...

`[info] Trying to connect node :nonode@nohost to: nil`

I'm following the example here:

https://github.com/exponentially/extreme_system_example/blob/1dafaf5c3202fbd9ff0092b7be399e5391559bd7/apps/api/lib/api.ex

**Comment by drozzy** [comment]
Ok, it seems like `extreme_system` is assuming configuration is stored in:

`:extreme_system, :nodes`

by default. It calls this before it calls _start, so my:

`event_store_settings = Application.get_env :extreme, :event_store`

has no effect.

**Comment by drozzy** [comment]
Oh wait, no, it's some sort of config:

```
config :extreme_system, :nodes, [
    "ExSysApi", "ExSysUsers"
  ]
```
Not sure what this is.. App names?

**Comment by drozzy** [comment]
Ok, after defining the config thing above, it works.

**Comment by burmajam** [comment]
This configuration is set in repo_root/config/dev.exs. Just one way to connect beams in cluster. I suggest to use :libcluster for something more serious.
