### ISSUE TITLE
How to return an error from aggregate?

### ISSUE THREAD

**Issue by drozzy** [exponentially/extreme_system#11]
I wanted to have a generic `handle_exec` in my aggregate, that would return `error`:

```
  def handle_exec({cmd, _payload}, from, state) do
    {:noblock, from, {:error, "Can't execute #{inspect cmd}."}, state}
  end
```

But it seems it's never matched:
` no function clause matching `

Any ideas?

**Comment by drozzy** [comment]
Weird... it won't even match if I put it first!

**Comment by drozzy** [comment]
Ok, after switching to `handle_cmd` helpers things are working ok now.

Returning errors like this:

```
{:noblock, from, {:error, Vex.errors(cmd) }, state}
```

**Comment by burmajam** [comment]
Yeah, that's the way to return catch-all error
