### ISSUE TITLE
How to ensure Extreme is started for projections

### ISSUE THREAD

**Issue by drozzy** [exponentially/extreme_system#13]
In my app, I have some projections.

They depend on Extreme. However, it seems like `extreme_system` is already starting extreme process (which registers itself under `Extreme` name globally).

But if I try to subscribe right away, I get an error:

`* (FunctionClauseError) no function clause matching in Extreme.System.EventStore.handle_call/3`

It almost seems like my projection is calling `read_and_stay_subscribed` earlier than extreme has a chance to start.

Is there any way around this you could suggest? Thanks.

**Comment by drozzy** [comment]
Strangely, chaining the name under which extreme starts from `MyAppName.Extreme` to something else worked.

**Comment by burmajam** [comment]
If you start two extreme connections either from the same application or including dependencies you need to name them differently.
