### ISSUE TITLE
Unit testing mock?

### ISSUE THREAD

**Issue by drozzy** [exponentially/extreme_system#14]
Loving the system so far. Is there any easy way to do unit testing on aggregates?

E.g. given this command ensure these events are emitted? Or maybe even on the level of the Facade itself?

Thanks!

**Comment by drozzy** [comment]
Was unable to pass the "dry_run" parameter, but unit tests work great nonetheless:

```
	test "ensure new process can be started", %{process: agg} do
		id = UUID.uuid4()
		evt = %ProcessStarted{process_id: id}
		cmd = {id, evt}

		assert {:ok, _, [cmd], _, _} = Process.new_process(agg, cmd)
	end	
```

**Comment by burmajam** [comment]
Sorry, I've missed this issue, I'm glad you like system so far :)

If you have `"dry_run" => true` in command params your command will be processed normally and if everything is ok *it will not persist events* but return `{:ok, state.version}`. It is useful for front-end validation for example. That way they won't emit events but only check if command can be executed.

You can also set `"dry_run" => :verbose`. In that case events won't be emitted as well but you'll get `{:ok, list_of_events_that_would_be_emitted}` back. I use it sometimes when I'm trying some commands on dev env using Postman or something similar.

**Comment by burmajam** [comment]
Regarding testing aggregates it's really easy with GenAggregate. Here's one example:

```elixir
    test "User.Registered and ProfileSet events are emitted when command is valid" do
      pid   = _spawn_aggregate()
      id    = _generate_id
      cmd   = Commands.register_user

      assert {:ok, transaction_id, events, last_version, _} = Aggregate.register_user(pid, cmd, id, [])

      assert [
        %Event.Registered{id: ^id}=e1,
        %Event.ProfileSet{id: ^id}=e2
      ] = events
      assert e1.email      == cmd["email"]
      assert e1.username   == cmd["username"]

      assert e2.first_name == cmd["first_name"]
      assert e2.last_name  == cmd["last_name"]

      assert last_version  == -1
      assert {:ok, _state} = Aggregate.commit(pid, transaction_id, last_version, 1)
    end
```

**Comment by drozzy** [comment]
Thanks for the example!

**Comment by drozzy** [comment]
While the "new" command works, for some reason, I can't seem to unit test commands that route to __existing__ aggregate. It just hangs there..

**Comment by drozzy** [comment]
This is very strange... I keep getting `:commit_timeout` if I try to route a command in the unit test to an existing aggregate.

**Comment by drozzy** [comment]
Ooooo! I was missing the `commit` line!

```
assert {:ok, _state} = Aggregate.commit(pid, transaction_id, last_version, 1)
```

Without it we can execute the __next__ command.
