### ISSUE TITLE
Default aggregate identity id inside an event?

### ISSUE THREAD

**Issue by drozzy** [exponentially/extreme_system#16]
Is the default aggregate identity name assumed to be `id` inside an event?

I'm getting:

```
key "id" not found in:
```

Maybe because my event has aggregate identity stored inside `my_id` field instead?
I'm using:

`proxy_to_new_aggregate` and `proxy_to_aggregate` helpers.

**Comment by burmajam** [comment]
Are :new_cmd and :my_command two different commands? I guess they are, but id field in each command can be different. I guess I'm missing connection between those two in your case

**Comment by drozzy** [comment]
They are different commands but id field is named the same. In real system it might be named something like “exam-id” - my point was that extreme is assuming it is named “id”. 

After setting above config it all works.
