### ISSUE TITLE
In-memory event store?

### ISSUE THREAD

**Issue by drozzy** [exponentially/extreme_system#17]
Is there any way to run a simple in-memory event store for a simple app?

I want a quick way to create an app, and don't want to spin-up eventstore. In-memory storage is fine, even if it is reset upon restart.

**Comment by burmajam** [comment]
You can override when_pid_is_not_registered/0 and save_events/3 functions in your message_handler. It would be better to make EventStore as adapter but I didn't make it that way (yet)

**Comment by drozzy** [comment]
Ok,  thanks.

Eventstore is hogging a lot of resources in my testing cloud deployment... it's a pita to run.
