### ISSUE TITLE
How to route different commands to different aggregate types?

### ISSUE THREAD

**Issue by drozzy** [exponentially/extreme_system#18]
I wanted to introduce a new aggregate into the system, but not sure how to do it in message handler.

I don't understand what "prefix" does. Does it match on incoming event-name? 

Here is my current message handler (with generic names put in). How would I add another aggregate (say, `AggTwo`?):
```
defmodule MyApp.Core.MessageHandler do
  alias   MyApp.Core.MyAgg

  use     Extreme.System.MessageHandler, prefix:        MyApp,
                                         aggregate_mod: MyAgg


  proxy_to_new_aggregate :new_cmd,       id: :myagg_id
  proxy_to_aggregate     :existing_cmd,  id: :myagg_id

end
```

**Comment by drozzy** [comment]
Also, what if two different aggregates have the _same_ command? E.g.: `MyCar.startup` and `Invoice.startup`?

I see that the `facade` only routes based on the command/function name... Maybe I'm wrong.

**Comment by drozzy** [comment]
Oooh... wait... there should be multiple facades...

**Comment by drozzy** [comment]
Nope.. can't start multiple facades...
```
** (Mix) Could not start application myapp: MyApp.Application.start(:normal, []) returned an error: bad child specification, more than one child specification has the id: Extreme.System.FacadeSup.
If using maps as child specifications, make sure the :id keys are unique.
If using a module or {module, arg} as child, use Supervisor.child_spec/2 to change the :id, for example:

    children = [
      Supervisor.child_spec({MyWorker, arg}, id: :my_worker_1),
      Supervisor.child_spec({MyWorker, arg}, id: :my_worker_2)
    ]
```

**Comment by drozzy** [comment]
Had luck writing one facade, with different command names for each aggregate.

Wish there was a better way so I could re-use same commands maybe.

Works for now. Still not clear if it's a good idea or even possible to spawn multiple facades.

**Comment by burmajam** [comment]
There should be one Facade per application, and if you really need more aggregates in one app, there should be MessageHandler per Aggregate. Then in facade you should expect :startup_car and :startup_invoice commands, but route them to :startup command on different message handler:

```
route(:startup_car, {CarMsgHandler, :startup})
route(:startup_invoce, {InvoiceMsgHandler, :startup})
```

**Comment by drozzy** [comment]
Ah, nice. I didn't realize facade could rename commands. But makes sense!
